package com.labwatcher.cmd;

import com.labwatcher.engine.EngineAdapter;
import com.labwatcher.engine.EngineAdapter.ParseSummary;
import com.labwatcher.model.ColumnStat;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.Parameters;

import java.io.PrintStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;
import java.util.concurrent.Callable;

/**
 * {@code lab-watcher infer-schema <file.csv>} — read a sample CSV through
 * the engine and emit a starter schema TOML with min/max bounds derived
 * from the observed column statistics, padded by a configurable margin.
 *
 * <p>Useful first step when onboarding a new instrument: dump a clean run,
 * run this command, hand-edit the generated file, then point
 * {@code lab-watcher watch} at the live data directory.
 */
@Command(name = "infer-schema",
    description = "Generate a starter schema TOML from a sample CSV.")
public final class InferSchemaCommand implements Callable<Integer> {

    @Parameters(index = "0", description = "Sample CSV to inspect.")
    private Path file;

    @Option(names = {"-o", "--output"},
        description = "Write the schema to this path instead of stdout.")
    private Path output;

    @Option(names = "--name",
        description = "Schema name (default: derived from filename).")
    private String name;

    @Option(names = "--margin", description =
        "Fractional padding around observed min/max (default: 0.10 = ±10%).")
    private double margin = 0.10;

    @Option(names = "--timestamp-column",
        description = "Name of the timestamp column (default: timestamp).")
    private String timestampColumn = "timestamp";

    @Override
    public Integer call() throws Exception {
        if (!Files.isRegularFile(file)) {
            System.err.println("error: file not found: " + file);
            return 2;
        }
        try {
            ParseSummary p = new EngineAdapter().parse(file);
            String toml = render(p);
            if (output != null) {
                Files.writeString(output, toml);
                System.out.println("wrote " + output);
            } else {
                System.out.print(toml);
            }
            return 0;
        } catch (UnsatisfiedLinkError e) {
            System.err.println("error: native engine not loaded.");
            return 3;
        }
    }

    /** Visible for tests: build the TOML body from a parse result. */
    String render(ParseSummary p) {
        String schemaName = name != null ? name : deriveName(file.getFileName().toString());
        StringBuilder b = new StringBuilder();
        b.append("# Generated by lab-watcher infer-schema\n");
        b.append("name = \"").append(schemaName).append("\"\n");
        b.append("version = \"0.1\"\n");
        b.append("require_timestamp_column = ")
         .append(hasColumn(p, timestampColumn)).append('\n');
        b.append("timestamp_column_name = \"").append(timestampColumn).append("\"\n");
        b.append("allow_extra_columns = true\n\n");

        for (ColumnStat c : p.columnStats()) {
            if (c.name().equals(timestampColumn)) continue;
            if (!"float".equals(c.type()) && !"integer".equals(c.type())) continue;
            if (c.min() == null || c.max() == null
                || c.min().isNaN() || c.max().isNaN()) continue;
            double lo = c.min(), hi = c.max();
            double pad = (hi - lo) * margin;
            if (pad == 0.0) pad = Math.abs(lo) * margin + 1.0;
            b.append("[[columns]]\n");
            b.append("name = \"").append(c.name()).append("\"\n");
            b.append("type = \"").append(c.type()).append("\"\n");
            b.append("required = true\n");
            b.append(String.format(Locale.ROOT, "min_value = %.4f%n", lo - pad));
            b.append(String.format(Locale.ROOT, "max_value = %.4f%n", hi + pad));
            b.append('\n');
        }
        return b.toString();
    }

    private static boolean hasColumn(ParseSummary p, String name) {
        for (String h : p.headers()) if (h.equals(name)) return true;
        return false;
    }

    private static String deriveName(String filename) {
        int dot = filename.lastIndexOf('.');
        String stem = dot > 0 ? filename.substring(0, dot) : filename;
        return stem.replaceAll("[^A-Za-z0-9_-]+", "-").toLowerCase(Locale.ROOT);
    }

    /** Test seam: redirect stdout. */
    @SuppressWarnings("unused")
    void setOut(PrintStream out) { System.setOut(out); }
}
